<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tbl_pengeluaran_model extends CI_Model
{

    public $table = 'tbl_pengeluaran';
    public $id = 'id_pengeluaran';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_pengeluaran,kategori,tanggal,nominal,keterangan,tbl_pengeluaran.id_users,full_name');
        $this->datatables->from('tbl_pengeluaran');
        //add this line for join
        $this->datatables->join('tbl_user', 'tbl_user.id_users = tbl_pengeluaran.id_users');
        $this->datatables->add_column('action', anchor(site_url('tbl_pengeluaran/read/$1'),'<i class="fa fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
            ".anchor(site_url('tbl_pengeluaran/update/$1'),'<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
                ".anchor(site_url('tbl_pengeluaran/delete/$1'),'<i class="fa fa-trash-o" aria-hidden="true"></i>','class="btn btn-danger btn-sm" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_pengeluaran');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->select('id_pengeluaran,tanggal,kategori,nominal,keterangan,tbl_pengeluaran.id_users,full_name');
        $this->db->join('tbl_user', 'tbl_user.id_users = tbl_pengeluaran.id_users');
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    function get_all_tanggal($tanggal_awal, $tanggal_akhir, $kategori)
    {
        $tanggal_awal = $this->db->escape($tanggal_awal);
        $tanggal_akhir = $this->db->escape($tanggal_akhir);
        $kategori = $this->db->escape($kategori);

        $this->db->select('id_pengeluaran,tanggal,kategori,nominal,keterangan,tbl_pengeluaran.id_users,full_name');
        $this->db->join('tbl_user', 'tbl_user.id_users = tbl_pengeluaran.id_users');
        $this->db->where('DATE(tanggal) BETWEEN '.$tanggal_awal.' AND '.$tanggal_akhir); 
        $this->db->where('kategori = ' .$kategori); 
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    function get_pengeluaran($tanggal, $bulan, $tahun) {
        $this->db->select('sum(nominal) AS hasil');
       
        $this->db->where('DAY(tanggal)', $tanggal);
        $this->db->where('MONTH(tanggal)', $bulan);
        $this->db->where('YEAR(tanggal)', $tahun);
        
        return $this->db->get("tbl_pengeluaran")->result();
    }

    
    function get_all_tanggal_semua($tanggal_awal, $tanggal_akhir)
    {
        $tanggal_awal = $this->db->escape($tanggal_awal);
        $tanggal_akhir = $this->db->escape($tanggal_akhir);

        $this->db->select('id_pengeluaran,tanggal,kategori,nominal,keterangan,tbl_pengeluaran.id_users,full_name');
        $this->db->join('tbl_user', 'tbl_user.id_users = tbl_pengeluaran.id_users');
        $this->db->where('DATE(tanggal) BETWEEN '.$tanggal_awal.' AND '.$tanggal_akhir);  
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }


    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_pengeluaran', $q);
	$this->db->or_like('tanggal', $q);
	$this->db->or_like('nominal', $q);
	$this->db->or_like('keterangan', $q);
	$this->db->or_like('id_users', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_pengeluaran', $q);
	$this->db->or_like('tanggal', $q);
	$this->db->or_like('nominal', $q);
	$this->db->or_like('keterangan', $q);
	$this->db->or_like('id_users', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Tbl_pengeluaran_model.php */
/* Location: ./application/models/Tbl_pengeluaran_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2023-07-05 17:32:59 */
/* http://harviacode.com */