<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tbl_barangmasuk_model extends CI_Model
{

    public $table = 'tbl_barangmasuk';
    public $id = 'id_masuk';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_masuk,id_barang,tbl_barangmasuk.tanggal_masuk,nama_produk,jumlah_masuk');
        $this->datatables->from('tbl_barangmasuk');
        //add this line for join
        $this->datatables->join('tbl_produk', 'tbl_produk.id_produk = tbl_barangmasuk.id_barang');
        $this->datatables->add_column('action', anchor(site_url('tbl_barangmasuk/read/$1'),'<i class="fa fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
            ".anchor(site_url('tbl_barangmasuk/update/$1'),'<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
                ".anchor(site_url('tbl_barangmasuk/delete/$1'),'<i class="fa fa-trash-o" aria-hidden="true"></i>','class="btn btn-danger btn-sm" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_masuk');
        return $this->datatables->generate();
    }

    function get_all_tanggal($tanggal_awal,$tanggal_akhir)
    {
        $tanggal_awal = $this->db->escape($tanggal_awal);
        $tanggal_akhir = $this->db->escape($tanggal_akhir);
        $this->db->select('id_masuk,id_barang,tbl_barangmasuk.tanggal_masuk,nama_produk,jumlah_masuk');
        $this->db->join('tbl_produk', 'tbl_produk.id_produk = tbl_barangmasuk.id_barang');
        $this->db->where('DATE(tbl_barangmasuk.tanggal_masuk) BETWEEN '.$tanggal_awal.' AND '.$tanggal_akhir); 
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get all
    function get_all()
    {
        $this->datatables->select('id_masuk,id_barang,tbl_barangmasuk.tanggal_masuk,nama_produk,jumlah_masuk');
        //add this line for join
        $this->datatables->join('tbl_produk', 'tbl_produk.id_produk = tbl_barangmasuk.id_barang');
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_masuk', $q);
	$this->db->or_like('id_barang', $q);
	$this->db->or_like('tanggal_masuk', $q);
	$this->db->or_like('jumlah_masuk', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_masuk', $q);
	$this->db->or_like('id_barang', $q);
	$this->db->or_like('tanggal_masuk', $q);
	$this->db->or_like('jumlah_masuk', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Tbl_barangmasuk_model.php */
/* Location: ./application/models/Tbl_barangmasuk_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2023-07-18 02:30:54 */
/* http://harviacode.com */